### ISSUE TITLE
Question about migration from Google Code to Github

### ISSUE THREAD

**Issue by daivanov** [bluezio/xeger#1]
I can see thee are some issue reported in 2010-2015 on Google Code page:
https://code.google.com/p/xeger/issues/list
Some of issues contain patches. Are these patched applied in GitHub repository?

**Comment by agarciadom** [comment]
I haven't applied any of those patches, sorry! This repository was there just to fix a particular bug that was blocking us, not as a replacement of the original repository.

Nevertheless, I wouldn't mind reviewing them as pull requests ;-).

**Comment by daivanov** [comment]
Yes, but the main question: do you plan to release it to maven central?

**Comment by agarciadom** [comment]
I could do it, after changing the groupId, of course. I wouldn't want to
have it confused with the releases of the original maintainer.

I've pushed some things to Central before: I hope I can still use the OSS
Sonatype repository, as usual.

**Comment by daivanov** [comment]
I didn't find any traces of xeger in maven central.

**Comment by agarciadom** [comment]
Sorry, you're right. I forgot that we simply had it uploaded to our own Nexus instance.

**Comment by agarciadom** [comment]
I have uploaded Xeger to my Bintray Maven repo, if it helps:

```
<repositories>
  <repository>
    <snapshots>
      <enabled>false</enabled>
    </snapshots>
    <id>bintray-bluezio-maven</id>
    <name>bintray</name>
    <url>https://dl.bintray.com/bluezio/maven</url>
  </repository>
</repositories>
```
