### ISSUE TITLE
依赖包找不到，求大神指导！！！！！！！！！

### ISSUE THREAD

**Issue by yangyuanchao** [bluezio/xeger#2]
compile group: 'javax.servlet', name:'javax.servlet-api', version:'3.1.0'
	compile group: 'nl.flotsam', name:'xeger', version:'1.0.0-SNAPSHOT'
	compile group: 'com.alibaba', name:'buc.sso.common', version:'0.4.4'
	compile group: 'com.alibaba', name:'buc.sso.client', version:'0.3.9'

**Comment by agarciadom** [comment]
Sorry, but I don't speak Chinese - could you explain your problem in English?

Google Translate says you have some dependency resolution issues: did you try installing this library into your local Maven repository by using `mvn install`, and then using it from your Gradle build?

**Comment by yangyuanchao** [comment]
I don't find the dependency(xeger),but now I find the source code.  
I don't find  dependencies(buc.sso.common, buc.sso.client),  can you help me?

**Comment by agarciadom** [comment]
Those are Alibaba libraries, which are not related to this project. I am afraid you will have to look elsewhere for them.

**Comment by agarciadom** [comment]
Closing as unrelated.
