### ISSUE TITLE
Bintray

### ISSUE THREAD

**Issue by michaelmior** [bluezio/xeger#7]
Since Bintray will be shutting down next week, how about using the [GitHub Pakage Registry](https://docs.github.com/en/packages/guides/configuring-apache-maven-for-use-with-github-packages) to host Maven builds? With a little bit of configuration, a snapshot build can be created on every commit to the master branch using GitHub Actions.

[This repository](https://github.com/michaelmior/) has an example of the necessary configuration. Basically there are three things necessary:

1. Add a `distributionManagement` section to `pom.xml` pointing to GitHub Packages.
2. Create an action to publish on every push to the `master` branch.
3. Create a [personal access token](https://docs.github.com/en/github/authenticating-to-github/creating-a-personal-access-token) so the action has permission to publish the package.

**Comment by dizzzz** [comment]
I'd appreciate it too..

**Comment by agarciadom** [comment]
I know it took me forever, but it's finally done: I have deployed version 1.0.2 to a GitHub Package Registry for this repository, and updated the README so it reflects it :-).

I believe there is also a 1.0.0 release on Maven Central, based on a fork of this repository:

https://search.maven.org/artifact/com.github.krraghavan/xeger/1.0.0-RELEASE/jar
